"""Add broker_order_id and fees to orders

Revision ID: 9b52455230ea
Revises: e6e50172564b
Create Date: 2026-04-05 19:47:13.336385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b52455230ea'
down_revision: Union[str, None] = 'e6e50172564b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('fees', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('broker_order_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'broker_order_id')
    op.drop_column('orders', 'fees')
    # ### end Alembic commands ###
