"""Add device quota backend limit

Revision ID: c3b7c02fc688
Revises: 36f986927a6c
Create Date: 2026-04-07 00:48:52.894023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3b7c02fc688'
down_revision: Union[str, None] = '36f986927a6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_quotas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('month_period', sa.String(), nullable=False),
    sa.Column('free_trades_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'month_period', name='uq_device_month')
    )
    op.create_index(op.f('ix_device_quotas_device_id'), 'device_quotas', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_quotas_id'), 'device_quotas', ['id'], unique=False)
    op.create_index(op.f('ix_device_quotas_month_period'), 'device_quotas', ['month_period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_quotas_month_period'), table_name='device_quotas')
    op.drop_index(op.f('ix_device_quotas_id'), table_name='device_quotas')
    op.drop_index(op.f('ix_device_quotas_device_id'), table_name='device_quotas')
    op.drop_table('device_quotas')
    # ### end Alembic commands ###
