"""add_simulation_columns

Revision ID: e830696b280c
Revises: 43a7bf3e6b62
Create Date: 2026-04-02 01:17:21.197059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e830696b280c'
down_revision: Union[str, None] = '43a7bf3e6b62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('simulation_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('simulation_start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('virtual_balance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'virtual_balance')
    op.drop_column('users', 'simulation_start_date')
    op.drop_column('users', 'simulation_active')
    # ### end Alembic commands ###
